export enum ActionType {
    COMBINED_ACTION = 'COMBINED_ACTION',
    SET_CLIENT_DETAILS = 'SET_CLIENT_DETAILS',
    SET_ACTIVE_SCREEN = 'SET_ACTIVE_SCREEN',
    SET_ACTIVE_CONTACT = 'SET_ACTIVE_CONTACT'
} 
